### ISSUE TITLE
Maintain parity with firehose telemetry for ES

### ISSUE THREAD

**Issue by blakebarnett** [postmates/cernan#275]
The ElasticSearch sink should provide an equivalent to: `cernan.sinks.firehose.records.total_delivered`

**Comment by blt** [comment]
To expand on this, the firshose sink has been in production for a while and has grown a fair bit of self-telemetry. Note the use of `report_full_telemetry`. It would be very valuable for transitions from firehose to direct elasticsearch to maintain this level of self-telemetry, though there will necessarily be adjustments due to context. 

Existing ES telemetry is fine we just need to add more.
