### ISSUE TITLE
How are you finding elastic-rs?

### ISSUE THREAD

**Issue by KodrAus** [postmates/cernan#280]
Hi there!

First off, sorry for making this an issue here. It's not a bug report or feature request. I see you're using `elastic` and I just wanted to know how you're finding it. Whether there are friction points in the API, things you don't like, things you wish it did, guarantees on stability you would like etc so I can make sure I keep your needs in mind while working on it.

I'm happy to take this over to an issue on `elastic` if you don't want the clutter here, and please jump up and down if I make any changes you don't like!

Thanks!

**Comment by blt** [comment]
@KodrAus hi! 

`elastic` has been great! I did have some early struggle trying to get auto-serialization running via serde but had to back off that on account of we don't have well-structured payloads to send. Every `LogLine` that goes through to the elasticsearch sink has two fields of unstructured data, `tags` which are set by configuration and `fields` which users can fiddle with via the programmable filters. Because of compatibility issues with kibana we need to drop these at the end of the body, rather than as nested objects. You can see us building the bodies here: https://github.com/postmates/cernan/blob/master/src/sink/elasticsearch.rs#L81

I guess the sink would have been a little shorter if there were serialization support for HashMap but that's about it. 

Thanks very much for `elastic`!

**Comment by KodrAus** [comment]
Thanks for the feedback!

Yeh, I can see short of implementing `Serialize` yourself and emitting the fields on that hashmap as fields on `LogLine` I don't think there's much more you can do to support extra fields at runtime. I've got the same issue for aggregations where sub aggregations are returned as fields on the bucket in the response.

I think it would be good to add some more `bulk` support, so maybe you can avoid having to construct the headers and `\n`s yourself.
